const ROLES = {
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  EMPLOYEE: 'EMPLOYEE'
};

const PERMISSIONS = {
  // News & Announcements
  CREATE_NEWS: ['ADMIN', 'MODERATOR'],
  EDIT_NEWS: ['ADMIN', 'MODERATOR'],
  DELETE_NEWS: ['ADMIN'],
  
  // Blogs
  CREATE_BLOG: ['ADMIN', 'MODERATOR', 'EMPLOYEE'],
  EDIT_OWN_BLOG: ['ADMIN', 'MODERATOR', 'EMPLOYEE'],
  EDIT_ANY_BLOG: ['ADMIN', 'MODERATOR'],
  DELETE_BLOG: ['ADMIN', 'MODERATOR'],
  
  // Discussions
  CREATE_DISCUSSION: ['ADMIN', 'MODERATOR', 'EMPLOYEE'],
  MODERATE_DISCUSSION: ['ADMIN', 'MODERATOR'],
  
  // Recognitions
  CREATE_RECOGNITION: ['ADMIN', 'MODERATOR', 'EMPLOYEE'],
  MANAGE_RECOGNITIONS: ['ADMIN', 'MODERATOR'],
  
  // Surveys
  CREATE_SURVEY: ['ADMIN', 'MODERATOR'],
  VIEW_SURVEY_RESULTS: ['ADMIN', 'MODERATOR'],
  
  // Learning & Development
  MANAGE_COURSES: ['ADMIN', 'MODERATOR'],
  ENROLL_COURSES: ['ADMIN', 'MODERATOR', 'EMPLOYEE'],
  
  // Analytics
  VIEW_ANALYTICS: ['ADMIN', 'MODERATOR'],
  
  // Users
  MANAGE_USERS: ['ADMIN'],
  VIEW_ALL_USERS: ['ADMIN', 'MODERATOR']
};

module.exports = { ROLES, PERMISSIONS };

