// Export all MongoDB models
module.exports = {
  Role: require('./Role'),
  User: require('./User'),
  Blog: require('./Blog'),
  BlogComment: require('./BlogComment'),
  Discussion: require('./Discussion'),
  DiscussionComment: require('./DiscussionComment'),
  Recognition: require('./Recognition'),
  SurveyModel: require('./SurveyModel'),
  SurveyResponse: require('./SurveyResponse'),
  Course: require('./Course'),
  Module: require('./Module'),
  UserCourse: require('./UserCourse'),
  Certificate: require('./Certificate'),
  Analytics: require('./Analytics'),
  Announcement: require('./Announcement'),
  Group: require('./Group'),
  GroupMember: require('./GroupMember'),
  GroupPost: require('./GroupPost'),
  GroupComment: require('./GroupComment'),
  UserPoints: require('./UserPoints'),
  RewardCatalog: require('./RewardCatalog'),
  Redemption: require('./Redemption'),
  Mentorship: require('./Mentorship'),
  Notification: require('./Notification'),
  RssSource: require('./RssSource'),
  RssCategory: require('./RssCategory'),
  DeviceToken: require('./DeviceToken'),
  NotificationLog: require('./NotificationLog')
};
