// Collection  short inspirational thoughts for the day
export const developerThoughts = [
  "Code is written once but read many times.",
  "Make it work, make it right, make it fast.",
  "Every bug teaches you something new.",
  "Clean code is a sign of respect for your team.",
  "Think before you code.",
  "Simple solutions scale better.",
  "Refactor early, refactor often.",
  "Logs save lives in production.",
  "Write code your future self will thank you for.",
  "Tests are your safety net.",
  "Small improvements compound over time.",
  "Understand the problem deeply before solving it.",
  "Readable code is maintainable code.",
  "Automate repetitive tasks.",
  "Good naming is powerful design.",
  "Ship value, then iterate.",
  "Break complex problems into smaller pieces.",
  "Consistency beats clever tricks.",
  "Design for change, not perfection.",
  "Debug patiently, not emotionally.",
  "Every line of code adds responsibility.",
  "Optimize only after measuring.",
  "Focus on solving real problems.",
  "Documentation prevents confusion.",
  "Code reviews improve everyone.",
  "Technical debt compounds — manage it wisely.",
  "Learn something new every day.",
  "Understand trade-offs before deciding.",
  "Keep functions small and focused.",
  "Avoid premature optimization.",
  "Fail fast, learn faster.",
  "Build systems that are easy to debug.",
  "Good architecture enables speed.",
  "Keep dependencies minimal.",
  "Clarity beats complexity.",
  "Ask questions when unsure.",
  "Version control is your safety net.",
  "Think about edge cases.",
  "Write tests for critical paths.",
  "Measure success by impact.",
  "Performance matters at scale.",
  "Security is everyone’s responsibility.",
  "Review assumptions regularly.",
  "Keep learning new tools.",
  "Design with users in mind.",
  "Build resilient systems.",
  "Plan before implementing.",
  "Avoid duplication whenever possible.",
  "Stay curious about how things work.",
  "Learn from production incidents.",
  "Keep improving code quality.",
  "Be patient with difficult bugs.",
  "Understand before optimizing.",
  "Keep deployments simple.",
  "Monitor what you build.",
  "Focus on long-term maintainability.",
  "Prefer explicit over implicit.",
  "Write meaningful commit messages.",
  "Test edge cases thoroughly.",
  "Reduce complexity whenever possible.",
  "Collaborate openly with teammates.",
  "Take ownership of your code.",
  "Respect backward compatibility.",
  "Design APIs thoughtfully.",
  "Use tools wisely.",
  "Prioritize reliability.",
  "Build with empathy for users.",
  "Keep feedback loops short.",
  "Don’t ignore warnings.",
  "Keep improving your workflow.",
  "Understand the system as a whole.",
  "Code with intention.",
  "Be consistent across the codebase.",
  "Think about scalability early.",
  "Review code carefully.",
  "Keep learning fundamentals.",
  "Balance speed and quality.",
  "Learn from mistakes.",
  "Stay calm during outages.",
  "Simplify wherever possible.",
  "Choose clarity over cleverness.",
  "Maintain good coding standards.",
  "Write defensive code.",
  "Communicate clearly with your team.",
  "Keep improving documentation.",
  "Understand user needs.",
  "Make debugging easier.",
  "Keep systems observable.",
  "Avoid unnecessary complexity.",
  "Be proactive about improvements.",
  "Think about maintainers.",
  "Test before deploying.",
  "Review performance regularly.",
  "Keep systems secure.",
  "Focus on continuous improvement.",
  "Respect code ownership.",
  "Learn from peers.",
  "Build software that lasts.",
  "Strive for excellence in every commit.",
  "If it works, understand why.",
  "If it breaks, understand deeper.",
  "Great developers simplify complexity.",
  "Debugging is detective work.",
  "Your code is your reputation.",
  "Don’t just code — design.",
  "Think in systems, not features.",
  "Every refactor is an investment.",
  "Automation is a superpower.",
  "Measure before you optimize.",
  "Production is the ultimate test.",
  "Read errors carefully — they tell stories.",
  "Keep learning — tech evolves daily.",
  "Build for humans first.",
  "Comments explain why, not what.",
  "Naming things well saves hours.",
  "Good code feels obvious.",
  "Ship small, ship often.",
  "Reduce cognitive load.",
  "The best code is simple.",
  "Progress beats perfection.",
  "Slow is smooth, smooth is fast.",
  "Break things safely.",
  "Design for failure.",
  "Expect the unexpected.",
  "Be kind in code reviews.",
  "Software is a team sport.",
  "Curiosity drives innovation.",
  "Learn the fundamentals deeply.",
  "Tools change, principles remain.",
  "Code is communication.",
  "Fix root causes, not symptoms.",
  "Refactoring is cleaning.",
  "Complexity hides bugs.",
  "Keep mental models clear.",
  "Don’t fear legacy code — improve it.",
  "Observe before acting.",
  "Measure twice, deploy once.",
  "Write less, achieve more.",
  "Every outage teaches resilience.",
  "Plan for scale.",
  "Think long term.",
  "Quality saves time.",
  "Be proud of readable code.",
  "Keep builds fast.",
  "Automate testing early.",
  "Good engineers reduce risk.",
  "Focus on outcomes.",
  "Learn to debug efficiently.",
  "Practice makes patterns obvious.",
  "Keep improving daily.",
  "Solve problems, not just tickets.",
  "Engineering is continuous learning.",
  "Understand constraints.",
  "Make systems predictable.",
  "Stability builds trust.",
  "Simplicity scales.",
  "Keep curiosity alive.",
  "Don’t guess — verify.",
  "Code reviews are learning moments.",
  "Great software evolves.",
  "Think like a user.",
  "Eliminate friction.",
  "Keep feedback frequent.",
  "Avoid overengineering.",
  "Be pragmatic.",
  "Celebrate small wins.",
  "Learn from failures.",
  "Keep experiments small.",
  "Iterate constantly.",
  "Value clarity.",
  "Be intentional with design.",
  "Communicate assumptions.",
  "Protect production.",
  "Respect the craft.",
  "Sharpen your problem-solving skills.",
  "Be patient with complexity.",
  "Learn from debugging sessions.",
  "Think critically.",
  "Stay humble — software is complex.",
  "Understand performance bottlenecks.",
  "Make systems transparent.",
  "Keep improving architecture.",
  "Think beyond code.",
  "Learn to read code well.",
  "Balance innovation with stability.",
  "Question assumptions.",
  "Keep designs flexible.",
  "Improve incrementally.",
  "Keep momentum.",
  "Focus on value delivery.",
  "Think before committing.",
  "Be disciplined.",
  "Refactor mercilessly when needed.",
  "Stay adaptable.",
  "Keep your tools sharp.",
  "Learn continuously.",
  "Focus on simplicity.",
  "Be thoughtful.",
  "Deliver reliably.",
  "Improve communication.",
  "Seek feedback.",
  "Think deeply.",
  "Keep experimenting.",
  "Stay motivated.",
  "Write code with purpose.",
  "Keep learning from others.",
  "Stay curious about systems.",
  "Build things that matter.",
  "Enjoy solving hard problems."
]

/**
 * Get a random thought of the day based on the current date
 * This ensures the same thought is shown throughout the day
 * @returns {string} A random thought
 */
export const getThoughtOfTheDay = () => {
  const today = new Date()
  const dayOfYear = Math.floor((today - new Date(today.getFullYear(), 0, 0)) / 1000 / 60 / 60 / 24)
  const index = dayOfYear % thoughtsOfTheDay.length
  return thoughtsOfTheDay[index]
}





